name: NewPlugin
version: '1.0-SNAPSHOT'
main: me.legrid.newplugin.NewPlugin
authors: [ Legrid ]
description: MyPlugin
commands:
  openmenu:
    description: Гей?
    usage: </command>
  givehelmetsupport:
    description: Гей?
    usage: </command>



